[pytest]
DJANGO_SETTINGS_MODULE = BetRent.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
norecursedirs = .git .venv venv env static media staticfiles
