# Generated by Django 5.2.9 on 2026-05-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
