# Generated by Django 5.2.9 on 2026-05-30 05:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('listings', '0002_listingimage_image_alter_listingimage_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_days', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_ref', models.CharField(blank=True, max_length=100, unique=True)),
                ('checkout_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='listing',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-is_featured', '-created_at'], name='listings_li_is_feat_a41c33_idx'),
        ),
        migrations.AddField(
            model_name='promotionpayment',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_payments', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='promotionpayment',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
