# Generated by Django 5.2.9 on 2026-06-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_promotionpayment_alter_listing_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_premium_post',
            field=models.BooleanField(default=False),
        ),
    ]
