# Generated by Django 5.2.9 on 2026-06-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('pending_email', 'Pending Email Verification'), ('pending_payment', 'Pending Payment Verification'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending_email', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
