# Generated by Django 5.2.9 on 2026-06-20 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_account_status_user_email_verified_and_more'),
        ('subscriptions', '0002_seed_default_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='landlord_plan',
            field=models.ForeignKey(blank=True, help_text='Selected subscription plan for landlord accounts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landlord_users', to='subscriptions.subscriptionplan'),
        ),
    ]
